spring:
  redis:
    database: 1
    host: localhost
    port:
    password:
    timeout: 3s
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
server:
  port: 8081